import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const uiDir = path.resolve(__dirname, '../src/components/ui')
const indexPath = path.join(uiDir, 'index.ts')

const EXCLUDE = new Set([
  'index.ts',
  'index.tsx',
])

function shouldExclude(file: string): boolean {
  if (EXCLUDE.has(file)) return true
  if (file.endsWith('.test.tsx') || file.endsWith('.test.ts')) return true
  if (file.endsWith('.stories.tsx') || file.endsWith('.stories.ts')) return true
  if (file.endsWith('.spec.tsx') || file.endsWith('.spec.ts')) return true
  return false
}

export interface ComponentInfo {
  module: string
  symbols: string[]
  typeSymbols: string[]
}

function parseComponentFile(filePath: string): ComponentInfo | null {
  const content = fs.readFileSync(filePath, 'utf-8')
  const symbols: string[] = []
  const typeSymbols: string[] = []

  const exportFuncPattern = /^export\s+function\s+(\w+)/gm
  let match: RegExpExecArray | null
  while ((match = exportFuncPattern.exec(content)) !== null) {
    symbols.push(match[1])
  }

  const exportConstPattern = /^export\s+const\s+(\w+)/gm
  while ((match = exportConstPattern.exec(content)) !== null) {
    symbols.push(match[1])
  }

  if (symbols.length === 0) return null

  const typeDefPattern = /^export\s+(?:type\s+)?(?:interface|type)\s+(\w+)/gm
  while ((match = typeDefPattern.exec(content)) !== null) {
    const name = match[1]
    typeSymbols.push(name)
  }

  return {
    module: path.basename(filePath, path.extname(filePath)),
    symbols,
    typeSymbols,
  }
}

function generateBarrel(components: ComponentInfo[]): string {
  const lines: string[] = []
  lines.push('// auto-generated by scripts/generate-barrel.ts')
  lines.push('')
  lines.push("// Import global styles so consumers get design tokens out of the box")
  lines.push("import '../../styles/globals.css'")
  lines.push('')

  for (const comp of components) {
    if (comp.symbols.length === 1) {
      lines.push(`export { ${comp.symbols[0]} } from './${comp.module}'`)
    } else {
      lines.push(`export {`)
      comp.symbols.forEach((s, i) => {
        const comma = i < comp.symbols.length - 1 ? ',' : ''
        lines.push(`  ${s}${comma}`)
      })
      lines.push(`} from './${comp.module}'`)
    }
  }

  lines.push('')

  for (const comp of components) {
    if (comp.typeSymbols.length === 0) continue
    if (comp.typeSymbols.length === 1) {
      lines.push(`export type { ${comp.typeSymbols[0]} } from './${comp.module}'`)
    } else {
      lines.push(`export type {`)
      comp.typeSymbols.forEach((s, i) => {
        const comma = i < comp.typeSymbols.length - 1 ? ',' : ''
        lines.push(`  ${s}${comma}`)
      })
      lines.push(`} from './${comp.module}'`)
    }
  }

  return lines.join('\n') + '\n'
}

function main() {
  const files = fs
    .readdirSync(uiDir)
    .filter((f) => f.endsWith('.tsx') && !shouldExclude(f))
    .sort()

  const components: ComponentInfo[] = []

  for (const file of files) {
    const info = parseComponentFile(path.join(uiDir, file))
    if (info) {
      components.push(info)
    }
  }

  const barrel = generateBarrel(components)
  fs.writeFileSync(indexPath, barrel, 'utf-8')
  console.log(`Generated barrel file: ${indexPath}`)
  console.log(`Included ${components.length} component files`)
}

main()
