// auto-generated by scripts/generate-barrel.ts

// Import global styles so consumers get design tokens out of the box
import '../../styles/globals.css'

export {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent
} from './accordion'
export {
  AlertDialog,
  AlertDialogTrigger,
  AlertDialogPortal,
  AlertDialogHeader,
  AlertDialogFooter,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogOverlay,
  AlertDialogContent
} from './alert-dialog'
export { Alert } from './alert'
export { AspectRatio } from './aspect-ratio'
export { Avatar } from './avatar'
export { Badge } from './badge'
export { Box } from './box'
export { Breadcrumb } from './breadcrumb'
export { ButtonGroup } from './button-group'
export { Button } from './button'
export { Calendar } from './calendar'
export {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter
} from './card'
export {
  Carousel,
  CarouselItem,
  CarouselPrevious,
  CarouselNext,
  CarouselContent
} from './carousel'
export {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
  ChartLegend,
  ChartLegendContent
} from './chart'
export { Checkbox } from './checkbox'
export {
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent
} from './collapsible'
export { Combobox } from './combobox'
export {
  Command,
  CommandDialog,
  CommandInput,
  CommandList,
  CommandEmpty,
  CommandGroup,
  CommandSeparator,
  CommandItem,
  CommandShortcut
} from './command'
export {
  ContextMenu,
  ContextMenuTrigger,
  ContextMenuPortal,
  ContextMenuSub,
  ContextMenuRadioGroup,
  ContextMenuSubTrigger,
  ContextMenuSubContent,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuCheckboxItem,
  ContextMenuRadioItem,
  ContextMenuLabel,
  ContextMenuSeparator,
  ContextMenuShortcut
} from './context-menu'
export { DataTable } from './data-table'
export { DatePicker } from './date-picker'
export {
  Dialog,
  DialogTrigger,
  DialogPortal,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
  DialogOverlay
} from './dialog'
export {
  DirectionProvider,
  useDirection
} from './direction'
export {
  Drawer,
  DrawerTrigger,
  DrawerPortal,
  DrawerClose,
  DrawerOverlay,
  DrawerContent,
  DrawerHeader,
  DrawerFooter,
  DrawerTitle,
  DrawerDescription
} from './drawer'
export {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuGroup,
  DropdownMenuPortal,
  DropdownMenuSub,
  DropdownMenuRadioGroup,
  DropdownMenuShortcut,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuCheckboxItem,
  DropdownMenuRadioItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuSubTrigger,
  DropdownMenuSubContent
} from './dropdown-menu'
export { EmbossBox } from './emboss-box'
export { Empty } from './empty'
export { Field } from './field'
export {
  Form,
  FormField,
  useFormField,
  FormItem,
  FormLabel,
  FormDescription,
  FormMessage,
  FormControl
} from './form'
export {
  HoverCard,
  HoverCardTrigger,
  HoverCardContent
} from './hover-card'
export {
  InputGroup,
  InputGroupAddon
} from './input-group'
export {
  InputOTPGroup,
  InputOTPSeparator,
  InputOTP,
  InputOTPSlot
} from './input-otp'
export { Input } from './input'
export {
  Item,
  ItemMedia,
  ItemContent,
  ItemTitle,
  ItemDescription,
  ItemActions
} from './item'
export { Kbd } from './kbd'
export { Knob } from './knob'
export { Label } from './label'
export {
  Menubar,
  MenubarMenu,
  MenubarTrigger,
  MenubarContent,
  MenubarItem,
  MenubarCheckboxItem,
  MenubarRadioItem,
  MenubarLabel,
  MenubarSeparator,
  MenubarShortcut,
  MenubarSub,
  MenubarSubTrigger,
  MenubarSubContent,
  MenubarGroup,
  MenubarPortal,
  MenubarRadioGroup
} from './menubar'
export { NativeSelect } from './native-select'
export {
  NavigationMenu,
  NavigationMenuList,
  NavigationMenuItem,
  NavigationMenuTrigger,
  NavigationMenuContent,
  NavigationMenuLink,
  NavigationMenuViewport
} from './navigation-menu'
export { Pagination } from './pagination'
export {
  Popover,
  PopoverTrigger,
  PopoverContent
} from './popover'
export { ProgressCircle } from './progress-circle'
export { Progress } from './progress'
export {
  RadioGroup,
  Radio
} from './radio'
export {
  ResizablePanelGroup,
  ResizablePanel,
  ResizableHandle
} from './resizable'
export {
  ScrollArea,
  ScrollBar
} from './scroll-area'
export {
  Select,
  SelectGroup,
  SelectValue,
  SelectContent,
  SelectItem,
  SelectLabel,
  SelectSeparator,
  SelectTrigger
} from './select'
export { Separator } from './separator'
export {
  Sheet,
  SheetTrigger,
  SheetClose,
  SheetPortal,
  SheetContent,
  SheetHeader,
  SheetFooter,
  SheetTitle,
  SheetDescription,
  SheetOverlay
} from './sheet'
export {
  SidebarProvider,
  Sidebar,
  SidebarHeader,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupLabel,
  SidebarGroupContent,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
  SidebarSeparator,
  SidebarTrigger,
  SidebarInset,
  SidebarRail
} from './sidebar'
export { Skeleton } from './skeleton'
export { Slider } from './slider'
export { Spinner } from './spinner'
export { Switch } from './switch'
export {
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableRow,
  TableHead,
  TableCell,
  TableCaption
} from './table'
export {
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent
} from './tabs'
export { Text } from './text'
export { Textarea } from './textarea'
export { TiltCard } from './tilt-card'
export {
  ToastProvider,
  ToastViewport,
  Toast,
  ToastAction,
  ToastClose,
  ToastTitle,
  ToastDescription
} from './toast'
export { Toaster } from './toaster'
export {
  Toggle,
  ToggleGroup,
  ToggleGroupItem
} from './toggle'
export {
  TooltipProvider,
  Tooltip,
  TooltipTrigger,
  TooltipContent
} from './tooltip'
export { Typography } from './typography'

export type {
  AccordionProps,
  AccordionItemProps,
  AccordionTriggerProps,
  AccordionContentProps
} from './accordion'
export type {
  AlertDialogProps,
  AlertDialogTriggerProps,
  AlertDialogPortalProps,
  AlertDialogOverlayProps,
  AlertDialogContentProps,
  AlertDialogHeaderProps,
  AlertDialogFooterProps,
  AlertDialogTitleProps,
  AlertDialogDescriptionProps,
  AlertDialogActionProps,
  AlertDialogCancelProps
} from './alert-dialog'
export type { AlertProps } from './alert'
export type { AspectRatioProps } from './aspect-ratio'
export type { AvatarProps } from './avatar'
export type { BadgeProps } from './badge'
export type { BoxProps } from './box'
export type {
  BreadcrumbItem,
  BreadcrumbProps
} from './breadcrumb'
export type { ButtonGroupProps } from './button-group'
export type { ButtonProps } from './button'
export type { CalendarProps } from './calendar'
export type {
  CardProps,
  CardHeaderProps,
  CardTitleProps,
  CardDescriptionProps,
  CardContentProps,
  CardFooterProps
} from './card'
export type {
  CarouselProps,
  CarouselContentProps,
  CarouselItemProps,
  CarouselPreviousProps,
  CarouselNextProps
} from './carousel'
export type {
  ChartContainerProps,
  ChartTooltipProps,
  ChartTooltipContentProps,
  ChartLegendProps,
  ChartLegendContentProps
} from './chart'
export type { CheckboxProps } from './checkbox'
export type {
  CollapsibleProps,
  CollapsibleTriggerProps,
  CollapsibleContentProps
} from './collapsible'
export type {
  ComboboxItem,
  ComboboxProps
} from './combobox'
export type {
  CommandProps,
  CommandDialogProps,
  CommandInputProps,
  CommandListProps,
  CommandEmptyProps,
  CommandGroupProps,
  CommandSeparatorProps,
  CommandItemProps,
  CommandShortcutProps
} from './command'
export type {
  ContextMenuProps,
  ContextMenuTriggerProps,
  ContextMenuPortalProps,
  ContextMenuSubProps,
  ContextMenuRadioGroupProps,
  ContextMenuSubTriggerProps,
  ContextMenuSubContentProps,
  ContextMenuContentProps,
  ContextMenuItemProps,
  ContextMenuCheckboxItemProps,
  ContextMenuRadioItemProps,
  ContextMenuLabelProps,
  ContextMenuSeparatorProps,
  ContextMenuShortcutProps
} from './context-menu'
export type { DataTableProps } from './data-table'
export type { DatePickerProps } from './date-picker'
export type {
  DialogProps,
  DialogTriggerProps,
  DialogPortalProps,
  DialogOverlayProps,
  DialogContentProps,
  DialogHeaderProps,
  DialogFooterProps,
  DialogTitleProps,
  DialogDescriptionProps
} from './dialog'
export type { DirectionProviderProps } from './direction'
export type {
  DrawerProps,
  DrawerTriggerProps,
  DrawerPortalProps,
  DrawerCloseProps,
  DrawerOverlayProps,
  DrawerContentProps,
  DrawerHeaderProps,
  DrawerFooterProps,
  DrawerTitleProps,
  DrawerDescriptionProps
} from './drawer'
export type {
  DropdownMenuProps,
  DropdownMenuTriggerProps,
  DropdownMenuGroupProps,
  DropdownMenuPortalProps,
  DropdownMenuSubProps,
  DropdownMenuRadioGroupProps,
  DropdownMenuContentProps,
  DropdownMenuItemProps,
  DropdownMenuCheckboxItemProps,
  DropdownMenuRadioItemProps,
  DropdownMenuLabelProps,
  DropdownMenuSeparatorProps,
  DropdownMenuShortcutProps,
  DropdownMenuSubTriggerProps,
  DropdownMenuSubContentProps
} from './dropdown-menu'
export type { EmptyProps } from './empty'
export type { FieldProps } from './field'
export type {
  FormProps,
  FormFieldProps,
  FormItemProps,
  FormLabelProps,
  FormControlProps,
  FormDescriptionProps,
  FormMessageProps
} from './form'
export type {
  HoverCardProps,
  HoverCardTriggerProps,
  HoverCardContentProps
} from './hover-card'
export type {
  InputGroupProps,
  InputGroupAddonProps
} from './input-group'
export type {
  InputOTPProps,
  InputOTPGroupProps,
  InputOTPSlotProps,
  InputOTPSeparatorProps
} from './input-otp'
export type { InputProps } from './input'
export type {
  ItemProps,
  ItemMediaProps,
  ItemContentProps,
  ItemTitleProps,
  ItemDescriptionProps,
  ItemActionsProps
} from './item'
export type { KbdProps } from './kbd'
export type { KnobProps } from './knob'
export type { LabelProps } from './label'
export type {
  MenubarProps,
  MenubarMenuProps,
  MenubarTriggerProps,
  MenubarContentProps,
  MenubarItemProps,
  MenubarCheckboxItemProps,
  MenubarRadioItemProps,
  MenubarLabelProps,
  MenubarSeparatorProps,
  MenubarShortcutProps,
  MenubarSubProps,
  MenubarSubTriggerProps,
  MenubarSubContentProps,
  MenubarGroupProps,
  MenubarPortalProps,
  MenubarRadioGroupProps
} from './menubar'
export type { NativeSelectProps } from './native-select'
export type {
  NavigationMenuProps,
  NavigationMenuListProps,
  NavigationMenuItemProps,
  NavigationMenuTriggerProps,
  NavigationMenuContentProps,
  NavigationMenuLinkProps,
  NavigationMenuViewportProps
} from './navigation-menu'
export type { PaginationProps } from './pagination'
export type {
  PopoverProps,
  PopoverTriggerProps,
  PopoverContentProps
} from './popover'
export type { ProgressCircleProps } from './progress-circle'
export type { ProgressProps } from './progress'
export type {
  RadioProps,
  RadioGroupProps
} from './radio'
export type {
  ResizablePanelGroupProps,
  ResizablePanelProps,
  ResizableHandleProps
} from './resizable'
export type {
  ScrollAreaProps,
  ScrollBarProps
} from './scroll-area'
export type {
  SelectProps,
  SelectGroupProps,
  SelectValueProps,
  SelectTriggerProps,
  SelectContentProps,
  SelectItemProps,
  SelectLabelProps,
  SelectSeparatorProps
} from './select'
export type { SeparatorProps } from './separator'
export type {
  SheetProps,
  SheetTriggerProps,
  SheetCloseProps,
  SheetPortalProps,
  SheetOverlayProps,
  SheetContentProps,
  SheetHeaderProps,
  SheetFooterProps,
  SheetTitleProps,
  SheetDescriptionProps
} from './sheet'
export type {
  SidebarProviderProps,
  SidebarProps,
  SidebarHeaderProps,
  SidebarContentProps,
  SidebarFooterProps,
  SidebarGroupProps,
  SidebarGroupLabelProps,
  SidebarGroupContentProps,
  SidebarMenuProps,
  SidebarMenuItemProps,
  SidebarMenuButtonProps,
  SidebarSeparatorProps,
  SidebarTriggerProps,
  SidebarInsetProps,
  SidebarRailProps
} from './sidebar'
export type { SkeletonProps } from './skeleton'
export type { SliderProps } from './slider'
export type { SpinnerProps } from './spinner'
export type { SwitchProps } from './switch'
export type {
  TableProps,
  TableHeaderProps,
  TableBodyProps,
  TableFooterProps,
  TableRowProps,
  TableHeadProps,
  TableCellProps,
  TableCaptionProps
} from './table'
export type {
  TabsProps,
  TabsListProps,
  TabsTriggerProps,
  TabsContentProps
} from './tabs'
export type { TextProps } from './text'
export type { TextareaProps } from './textarea'
export type { TiltCardProps } from './tilt-card'
export type {
  ToastProviderProps,
  ToastViewportProps,
  ToastProps,
  ToastActionProps,
  ToastCloseProps,
  ToastTitleProps,
  ToastDescriptionProps
} from './toast'
export type {
  ToggleProps,
  ToggleGroupProps,
  ToggleGroupItemProps
} from './toggle'
export type {
  TooltipProps,
  TooltipTriggerProps,
  TooltipContentProps
} from './tooltip'
export type {
  TypographyVariant,
  TypographyProps
} from './typography'

// ─── Hooks ───
export { useAnimation } from '../../hooks/use-animation'
export { useToast, toast } from '../../hooks/use-toast'
export { useKeyboardShortcut } from '../../hooks/use-keyboard-shortcut'
export type { KeyboardShortcutOptions, KeyModifier } from '../../hooks/use-keyboard-shortcut'

// ─── Animation Presets ───
// CSS utility classes are available at:
//   import 'vanguard-emboss-uikit/presets'
// (Requires bundler CSS support for sub-path imports.)
